version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017


volumes:
  mongo-data:
    driver: local
    name: mongo-data
 
